### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by jolyonralph** [droboports/screen#1]
Are there any instructions for installation anywhere?

Tried installing in droboapps - didn't unpack properly.

Tried manually moving files to /bin, /lib etc   and that didn't work.

install.sh doesn't do anything (empty file).

I'm not a **ix expert, help, please

**Comment by ricardopadilha** [comment]
You have to make sure that you are placing the TGZ file in the DroboApps share. Sometimes browsers like Safari will try to be "helpful" and unpack the TGZ files automatically for you, and thus breaking the install.

Try to download the app again using right click + save as. Make sure that what you are copying is a file whose name ends in tgz.

P.S.: This is not a support forum for general DroboApps usage. Please refer to www.drobospace.com for help on how to get DroboApps installed and running.
